---

- name: install admin_user bootstrap
  copy:
    src: admin_user_bootstrap
    dest: /etc/init.d/admin_user_bootstrap
    owner: root
    group: root
    mode: 0755
  notify:
    - set_admin

- name: enable admin_user bootstrap
  command: /usr/sbin/update-rc.d admin_user_bootstrap defaults 01
  args:
    chdir: /etc/init.d
    creates: /etc/rc2.d/S02admin_user_bootstrap

- name: install ec2 bootstrap
  copy:
    src: ec2_bootstrap
    dest: /etc/init.d/ec2_bootstrap
    owner: root
    group: root
    mode: 0755
  notify:
    - set_hostname

- name: enable ec2 bootstrap
  command: /usr/sbin/update-rc.d ec2_bootstrap defaults 01
  args:
    chdir: /etc/init.d
    creates: /etc/rc2.d/S02ec2_bootstrap

- name: disable IPv6 via gai.conf
  copy:
    src: gai.conf
    dest: /etc/gai.conf
    owner: root
    group: root
    mode: 0644

- name: hard disable ipv6 as a service (1)
  copy:
    src: disable-ipv6.service
    dest: /lib/systemd/system/disable-ipv6.service
    owner: root
    group: root
    mode: 0644

- name: hard disable ipv6 as a service (2)
  file:
    src: /lib/systemd/system/disable-ipv6.service
    dest: /etc/systemd/system/multi-user.target.wants/disable-ipv6.service
    state: link

- name: kick systemd
  command: "/bin/systemctl daemon-reload"


- name: fix dhcp generation of resolv.conf
  copy:
    src: consul-fix-dhclient
    dest: /etc/dhcp/dhclient-exit-hooks.d/consul-fix
    owner: root
    group: root
    mode: 0755
