#!/bin/bash

### BEGIN INIT INFO
# Provides:             admin_user_bootstrap
# Required-Start:       $remote_fs $syslog
# Required-Stop:        $remote_fs $syslog
# Default-Start:        2 3 4 5
# Default-Stop:
# Short-Description:    Setup the admin user ssh keys
### END INIT INFO


SSH_KEY=`/usr/bin/curl -s http://169.254.169.254/latest/meta-data/public-keys/0/openssh-key`

if [ "X${SSH_KEY}" != "X" ]; then
	echo $SSH_KEY > /home/admin/.ssh/authorized_keys
	chmod 0600 /home/admin/.ssh/authorized_keys
	chown -R admin:admin /home/admin/.ssh/
fi
