#!/bin/bash

### BEGIN INIT INFO
# Provides:             ec2_bootstrap
# Required-Start:       $remote_fs $syslog
# Required-Stop:        $remote_fs $syslog
# Default-Start:        2 3 4 5
# Default-Stop:
# Short-Description:    Setup the hostname to role specs
### END INIT INFO


ROLE=`/usr/local/bin/get_user_data -p role`
DOMAIN=`/usr/local/bin/get_user_data -p domain`
INSTANCE_ID=`/usr/bin/curl -s http://169.254.169.254/latest/meta-data/instance-id |awk -F '-' '{print $NF}'`
IP=`/usr/bin/curl -s http://169.254.169.254/latest/meta-data/local-ipv4`

if [ "X${ROLE}" != "X" ]; then

  if [ "X${DOMAIN}" == "X" ]; then
    DOMAIN="local"
  fi
  
  if [ $(grep -c $IP /etc/hosts) -ne 0 ] ; then
    X="y"
  else
    echo "${IP} ${ROLE}-${INSTANCE_ID} ${ROLE}-${INSTANCE_ID}.${DOMAIN}" >> /etc/hosts
  fi
  
  echo "${ROLE}-${INSTANCE_ID}.${DOMAIN}" > /etc/hostname
  hostname "${ROLE}-${INSTANCE_ID}.${DOMAIN}" > /dev/null

fi

# Handle the case where resolv.conf is not being properly parsed
if [ $(grep -c "[a-z]032node" /etc/resolv.conf) -gt 0 ]; then
  sed -i s/032node/\ node/g /etc/resolv.conf
fi
