#!/usr/bin/python

import json
import urllib2
import sys
import getopt

param = 'role'
URL = 'http://169.254.169.254/latest/user-data'

try:
    opts, args = getopt.getopt(sys.argv[1:],"p:")
except getopt.GetoptError:
    print >> sys.stderr,  'get_user_data -p <PARAMETER:optional'
    sys.exit(2)

for opt,arg in opts:
    if opt == '-p':
        param = arg

data = json.load(urllib2.urlopen(URL))

try:
    print data[param]
except KeyError:
    print >> sys.stderr,  'parameter ' + param + ' does not exist'
    sys.exit(2)
